project_id = "ytcrplsistsxfaxkfqqp"

[functions.approve-proof]
verify_jwt = false

[functions.request-proof-modification]
verify_jwt = false

[functions.get-proof-by-token]
verify_jwt = false

[functions.get-public-proof-details]
verify_jwt = false

[functions.handle-proof-decision]
verify_jwt = false

[functions.send-proof-notification]
verify_jwt = true

[functions.send-proof-to-client]
verify_jwt = true

[functions.send-submission-notification]
verify_jwt = true

[functions.test-submission-email]
verify_jwt = true