// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ytcrplsistsxfaxkfqqp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl0Y3JwbHNpc3RzeGZheGtmcXFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4ODMwNjcsImV4cCI6MjA2OTQ1OTA2N30.rzKPK9GPPOUbZvTaqequy7KK2pBwG7wvxBAfAW-rwoE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});